#!/usr/bin/env python3
"""Dumps a set of greetings as SVG paths, for the landing page's drift.

The single-glyph extractor next door can get away with the cmap: one code
point, one outline. A greeting cannot (नमस्ते is conjuncts and matras,
مرحبا joins, สวัสดี stacks marks), so every word here goes through HarfBuzz
first, and what gets baked is the shaped result: final glyph ids at their
final offsets, in visual order. This page sells correct shaping; its own
decorations do not get to skip it.

Coordinates stay in font space, y-up, like the glyph extractor's; only the
path syntax is SVG's. The page must not flip y.

Run: python3 Tools/extract_greeting_paths.py > page/greetings.js
"""

import json
import sys

import uharfbuzz as hb
from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

COVERAGE = "Tests/CoverageFonts~"

# Hello, around the world. One per script the hero already speaks for, short
# enough to stay readable when extruded and tumbled.
GREETINGS = [
    ("Hello!",      "Latin",      "Tests/Fonts/NotoSans.ttf"),
    ("Hola!",       "Latin",      "Tests/Fonts/NotoSans.ttf"),
    ("Ciao!",       "Latin",      "Tests/Fonts/NotoSans.ttf"),
    ("안녕",         "Hangul",     f"{COVERAGE}/NotoSansCJKkr-Regular.otf"),
    ("你好",         "Han",        f"{COVERAGE}/NotoSansCJKsc-Regular.otf"),
    ("こんにちは",    "Kana",       f"{COVERAGE}/NotoSansCJKjp-Regular.otf"),
    ("नमस्ते",       "Devanagari", f"{COVERAGE}/NotoSansDevanagari-Regular.ttf"),
    ("สวัสดี",       "Thai",       f"{COVERAGE}/NotoSansThai-Regular.ttf"),
    ("مرحبا",       "Arabic",     f"{COVERAGE}/NotoSansArabic-Regular.ttf"),
    ("Привет!",     "Cyrillic",   "Tests/Fonts/NotoSans.ttf"),
    ("שלום",        "Hebrew",     f"{COVERAGE}/NotoSansHebrew-Regular.ttf"),
    ("Γεια!",       "Greek",      "Tests/Fonts/NotoSans.ttf"),
]

_cache = {}


def load(path):
    if path not in _cache:
        blob = hb.Blob.from_file_path(path)
        face = hb.Face(blob)
        font = hb.Font(face)  # unscaled: positions come back in font units
        tt = TTFont(path, fontNumber=0, lazy=True)
        _cache[path] = (font, tt, tt.getGlyphSet(), tt["head"].unitsPerEm)
    return _cache[path]


def shape(text, path):
    """The whole word as one SVG path in font units, plus its advance width.

    HarfBuzz hands back glyphs in visual order (an RTL word arrives already
    reversed) with the pen deltas between them; all that is left is to walk
    the pen and stamp each outline where the shaper put it.
    """
    font, tt, glyphs, upem = load(path)
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(font, buf)

    pen = SVGPathPen(glyphs)
    x = y = 0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = tt.getGlyphName(info.codepoint)
        glyphs[name].draw(TransformPen(
            pen, Transform(1, 0, 0, 1, x + pos.x_offset, y + pos.y_offset)))
        x += pos.x_advance
        y += pos.y_advance
    return pen.getCommands(), upem, x


def main():
    out = []
    for text, script, path in GREETINGS:
        try:
            d, upem, width = shape(text, path)
        except Exception as error:
            print(f"failed {text!r}: {error}", file=sys.stderr)
            continue
        if not d.strip():
            print(f"empty outline for {text!r}", file=sys.stderr)
            continue
        out.append({"text": text, "script": script, "d": d,
                    "upem": upem, "width": width})

    print("// Generated by Tools/extract_greeting_paths.py. Do not edit by hand.")
    print("export const GREETINGS = " + json.dumps(out, ensure_ascii=False) + ";")


if __name__ == "__main__":
    main()
