#!/usr/bin/env python3
"""Generates Runtime/Core/Unicode/VerticalData.g.cs from the UCD.

Usage: python3 gen_vertical_tables.py <ucd-dir> <output.cs>
Needs, in <ucd-dir>: VerticalOrientation.txt.

Vertical_Orientation (UAX #50) is what decides, for one codepoint in a
vertical column, whether it stands as it does in the code charts or is
turned ninety degrees clockwise. R is the default for the whole of Unicode
and by far the largest class (Latin, Cyrillic, Greek, Devanagari,
everything written horizontally), so it is dropped from the table and the
lookup returns it for anything not listed. That leaves the CJK half of the
property, which is what this file is really carrying.
"""
import sys, os

MAX_CP = 0x110000

# The order VerticalOrientation mirrors in C#. R is index 0 and the default.
CLASSES = ("R", "U", "Tu", "Tr")
CLASS2IDX = {n: i for i, n in enumerate(CLASSES)}


def parse(path):
    """Yields (lo, hi, value) for the semicolon-delimited property file."""
    with open(path, encoding="utf-8") as f:
        for line in f:
            body = line.split("#")[0].strip()
            if not body or ";" not in body:
                continue
            cps, value = [x.strip() for x in body.split(";")[:2]]
            lo, hi = (cps.split("..") + [None])[:2]
            lo = int(lo, 16)
            yield lo, int(hi, 16) if hi else lo, value


def ranges(table, default):
    """Merges a per-codepoint table into sorted ranges, dropping the default."""
    out = []
    for cp in range(MAX_CP):
        v = table[cp]
        if v == default:
            continue
        if out and out[-1][1] == cp - 1 and out[-1][2] == v:
            out[-1][1] = cp
        else:
            out.append([cp, cp, v])
    return out


def version_of(path):
    with open(path, encoding="utf-8") as f:
        first = f.readline()
        if "-" in first:
            return first.split("-", 1)[1].split(".txt")[0]
    return "unknown"


def main():
    ucd, out = sys.argv[1], sys.argv[2]
    source = os.path.join(ucd, "VerticalOrientation.txt")

    orientation = [CLASS2IDX["R"]] * MAX_CP
    for lo, hi, value in parse(source):
        idx = CLASS2IDX[value]
        for cp in range(lo, hi + 1):
            orientation[cp] = idx

    rows = ranges(orientation, CLASS2IDX["R"])
    starts = ",".join(f"0x{lo:X}" for lo, _, _ in rows)
    ends = ",".join(f"0x{hi:X}" for _, hi, _ in rows)
    values = ",".join(str(v) for _, _, v in rows)

    with open(out, "w", encoding="utf-8") as f:
        f.write(f"""// <auto-generated>
// Generated by Tools/gen_vertical_tables.py from the Unicode Character
// Database (VerticalOrientation, UCD version {version_of(source)}).
// Data (c) Unicode, Inc., distributed under the Unicode License v3
// (https://www.unicode.org/license.txt). Do not edit by hand.
// </auto-generated>

namespace OneText.Unicode
{{
    internal static class VerticalData
    {{
        // Sorted, non-overlapping ranges; codepoints outside them are R,
        // which is the property's own default for all of Unicode.
        private static readonly int[] RangeStarts = {{{starts}}};
        private static readonly int[] RangeEnds = {{{ends}}};
        private static readonly byte[] RangeValues = {{{values}}};

        /// <summary>Vertical_Orientation (UAX #50). Codepoints not listed are R.</summary>
        public static VerticalOrientation GetOrientation(int codepoint)
        {{
            int lo = 0, hi = RangeStarts.Length - 1;
            while (lo <= hi)
            {{
                int mid = (lo + hi) >> 1;
                if (codepoint < RangeStarts[mid]) hi = mid - 1;
                else if (codepoint > RangeEnds[mid]) lo = mid + 1;
                else return (VerticalOrientation)RangeValues[mid];
            }}
            return VerticalOrientation.Rotated;
        }}
    }}
}}
""")
    print(f"vertical={len(rows)} -> {out}")


if __name__ == "__main__":
    main()
