#!/usr/bin/env python3
"""Generates Runtime/Core/Unicode/BidiData.g.cs from UCD data files.

Usage: python3 gen_bidi_tables.py <ucd-dir> <output.cs>
Needs: DerivedBidiClass.txt, BidiBrackets.txt in <ucd-dir>.
"""
import sys, os

CLASSES = "L R AL EN ES ET AN CS NSM BN B S WS ON LRE RLE LRO RLO PDF LRI RLI FSI PDI".split()
NAME2CLS = {n: i for i, n in enumerate(CLASSES)}


def load_ranges(ucd):
    ranges = []
    with open(os.path.join(ucd, "DerivedBidiClass.txt")) as f:
        for line in f:
            missing = line.startswith("# @missing:")
            if missing:
                line = line[len("# @missing:"):]
            body = line.split("#")[0].strip()
            if not body or ";" not in body:
                continue
            cps, cls = [x.strip() for x in body.split(";")[:2]]
            if cls not in NAME2CLS:
                continue
            lo, hi = (cps.split("..") + [None])[:2]
            lo = int(lo, 16)
            hi = int(hi, 16) if hi else lo
            ranges.append((lo, hi, NAME2CLS[cls], missing))

    table = {}
    for lo, hi, cls, missing in ranges:  # non-L defaults first (L is the global default)
        if missing and cls != NAME2CLS["L"]:
            for cp in range(lo, hi + 1):
                table[cp] = cls
    for lo, hi, cls, missing in ranges:  # assigned values overlay defaults
        if not missing:
            for cp in range(lo, hi + 1):
                table[cp] = cls

    # merge into sorted ranges, dropping L (the lookup default)
    merged = []
    for cp in sorted(table):
        cls = table[cp]
        if cls == NAME2CLS["L"]:
            continue
        if merged and merged[-1][1] == cp - 1 and merged[-1][2] == cls:
            merged[-1][1] = cp
        else:
            merged.append([cp, cp, cls])
    return merged


def load_brackets(ucd):
    rows = []
    with open(os.path.join(ucd, "BidiBrackets.txt")) as f:
        for line in f:
            body = line.split("#")[0].strip()
            if not body:
                continue
            cp, other, kind = [x.strip() for x in body.split(";")]
            rows.append((int(cp, 16), int(other, 16), kind == "o"))
    rows.sort()
    return rows


def main():
    ucd, out = sys.argv[1], sys.argv[2]
    ranges = load_ranges(ucd)
    brackets = load_brackets(ucd)

    starts = ",".join(f"0x{lo:X}" for lo, _, _ in ranges)
    ends = ",".join(f"0x{hi:X}" for _, hi, _ in ranges)
    classes = ",".join(str(cls) for _, _, cls in ranges)
    bcp = ",".join(f"0x{cp:X}" for cp, _, _ in brackets)
    bpair = ",".join(f"0x{o:X}" for _, o, _ in brackets)
    bopen = ",".join("true" if o else "false" for _, _, o in brackets)

    version = "unknown"
    with open(os.path.join(ucd, "DerivedBidiClass.txt")) as f:
        first = f.readline()
        if "-" in first:
            version = first.split("-", 1)[1].split(".txt")[0]

    with open(out, "w") as f:
        f.write(f"""// <auto-generated>
// Generated by Tools/gen_bidi_tables.py from the Unicode Character Database
// (DerivedBidiClass / BidiBrackets, UCD version {version}).
// Data © Unicode, Inc., distributed under the Unicode License v3
// (https://www.unicode.org/license.txt). Do not edit by hand.
// </auto-generated>

namespace OneText.Unicode
{{
    internal static class BidiData
    {{
        // Sorted, non-overlapping ranges; codepoints not covered are class L.
        private static readonly int[] RangeStarts = {{{starts}}};
        private static readonly int[] RangeEnds = {{{ends}}};
        private static readonly byte[] RangeClasses = {{{classes}}};

        private static readonly int[] BracketCodepoints = {{{bcp}}};
        private static readonly int[] BracketPaired = {{{bpair}}};
        private static readonly bool[] BracketIsOpen = {{{bopen}}};

        public static BidiClass GetClass(int codepoint)
        {{
            int lo = 0, hi = RangeStarts.Length - 1;
            while (lo <= hi)
            {{
                int mid = (lo + hi) >> 1;
                if (codepoint < RangeStarts[mid]) hi = mid - 1;
                else if (codepoint > RangeEnds[mid]) lo = mid + 1;
                else return (BidiClass)RangeClasses[mid];
            }}
            return BidiClass.L;
        }}

        public static bool TryGetBracket(int codepoint, out int paired, out bool isOpen)
        {{
            int lo = 0, hi = BracketCodepoints.Length - 1;
            while (lo <= hi)
            {{
                int mid = (lo + hi) >> 1;
                if (codepoint < BracketCodepoints[mid]) hi = mid - 1;
                else if (codepoint > BracketCodepoints[mid]) lo = mid + 1;
                else
                {{
                    paired = BracketPaired[mid];
                    isOpen = BracketIsOpen[mid];
                    return true;
                }}
            }}
            paired = 0;
            isOpen = false;
            return false;
        }}

        /// <summary>BD16 canonical equivalence for bracket matching.</summary>
        public static int CanonicalBracket(int codepoint) => codepoint switch
        {{
            0x3008 => 0x2329,
            0x3009 => 0x232A,
            _ => codepoint,
        }};
    }}
}}
""")
    print(f"ranges={len(ranges)} brackets={len(brackets)} -> {out}")


if __name__ == "__main__":
    main()
